
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label producto3;
	private global::Gtk.Label producto2;
	private global::Gtk.Label producto1;
	private global::Gtk.Entry p1;
	private global::Gtk.Entry p2;
	private global::Gtk.Entry p3;
	private global::Gtk.Label subtotal;
	private global::Gtk.Label iva;
	private global::Gtk.Label total;
	private global::Gtk.Entry tot;
	private global::Gtk.Entry Iva;
	private global::Gtk.Entry sub;
	private global::Gtk.Button limpiar;
	private global::Gtk.Button factura;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto3 = new global::Gtk.Label ();
		this.producto3.Name = "producto3";
		this.producto3.LabelProp = global::Mono.Unix.Catalog.GetString ("producto3");
		this.fixed1.Add (this.producto3);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto3]));
		w1.X = 21;
		w1.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto2 = new global::Gtk.Label ();
		this.producto2.Name = "producto2";
		this.producto2.LabelProp = global::Mono.Unix.Catalog.GetString ("producto2");
		this.fixed1.Add (this.producto2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto2]));
		w2.X = 20;
		w2.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto1 = new global::Gtk.Label ();
		this.producto1.Name = "producto1";
		this.producto1.LabelProp = global::Mono.Unix.Catalog.GetString ("producto1");
		this.fixed1.Add (this.producto1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto1]));
		w3.X = 23;
		w3.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p1 = new global::Gtk.Entry ();
		this.p1.CanFocus = true;
		this.p1.Name = "p1";
		this.p1.IsEditable = true;
		this.p1.InvisibleChar = '●';
		this.fixed1.Add (this.p1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p1]));
		w4.X = 112;
		w4.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p2 = new global::Gtk.Entry ();
		this.p2.CanFocus = true;
		this.p2.Name = "p2";
		this.p2.IsEditable = true;
		this.p2.InvisibleChar = '●';
		this.fixed1.Add (this.p2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p2]));
		w5.X = 111;
		w5.Y = 57;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p3 = new global::Gtk.Entry ();
		this.p3.CanFocus = true;
		this.p3.Name = "p3";
		this.p3.IsEditable = true;
		this.p3.InvisibleChar = '●';
		this.fixed1.Add (this.p3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p3]));
		w6.X = 116;
		w6.Y = 107;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.subtotal = new global::Gtk.Label ();
		this.subtotal.Name = "subtotal";
		this.subtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("subtotal");
		this.fixed1.Add (this.subtotal);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.subtotal]));
		w7.X = 20;
		w7.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.iva = new global::Gtk.Label ();
		this.iva.Name = "iva";
		this.iva.LabelProp = global::Mono.Unix.Catalog.GetString ("iva");
		this.fixed1.Add (this.iva);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.iva]));
		w8.X = 18;
		w8.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total = new global::Gtk.Label ();
		this.total.Name = "total";
		this.total.LabelProp = global::Mono.Unix.Catalog.GetString ("total");
		this.fixed1.Add (this.total);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total]));
		w9.X = 15;
		w9.Y = 249;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tot = new global::Gtk.Entry ();
		this.tot.CanFocus = true;
		this.tot.Name = "tot";
		this.tot.IsEditable = true;
		this.tot.InvisibleChar = '●';
		this.fixed1.Add (this.tot);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tot]));
		w10.X = 119;
		w10.Y = 247;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Iva = new global::Gtk.Entry ();
		this.Iva.CanFocus = true;
		this.Iva.Name = "Iva";
		this.Iva.IsEditable = true;
		this.Iva.InvisibleChar = '●';
		this.fixed1.Add (this.Iva);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Iva]));
		w11.X = 116;
		w11.Y = 198;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.sub = new global::Gtk.Entry ();
		this.sub.CanFocus = true;
		this.sub.Name = "sub";
		this.sub.IsEditable = true;
		this.sub.InvisibleChar = '●';
		this.fixed1.Add (this.sub);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.sub]));
		w12.X = 120;
		w12.Y = 148;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.limpiar = new global::Gtk.Button ();
		this.limpiar.CanFocus = true;
		this.limpiar.Name = "limpiar";
		this.limpiar.UseUnderline = true;
		this.limpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.limpiar);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.limpiar]));
		w13.X = 239;
		w13.Y = 335;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.factura = new global::Gtk.Button ();
		this.factura.CanFocus = true;
		this.factura.Name = "factura";
		this.factura.UseUnderline = true;
		this.factura.Label = global::Mono.Unix.Catalog.GetString ("Factura");
		this.fixed1.Add (this.factura);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.factura]));
		w14.X = 96;
		w14.Y = 337;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 500;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.limpiar.Clicked += new global::System.EventHandler (this.OnLimpiarClicked);
		this.factura.Clicked += new global::System.EventHandler (this.OnFacturaClicked);
	}
}
